services:
  rclonebrowser_service:
    image: totza2010/rclonebrowser:latest
    container_name: rclonebrowser
    ports:
      - "5804:5800"
    environment:
      - USER_ID=0
      - GROUP_ID=0
      - TZ=Asia/Bangkok
      - VNC_PASSWORD=password
      - INSTALL_PACKAGES=font-noto-cjk font-noto-all
      - KEEP_APP_RUNNING=true
      - APP_NICENESS=-20
    cap_add:
      - SYS_NICE
    volumes:
      - "/home/totza2010/.config/rclone:/config:rw"
      - "/mnt:/shared:rw"